### ISSUE TITLE
Not compatible with the version of your running IDE (IntelliJ IDEA 2022.1)

### ISSUE THREAD

**Issue by izzetince** [MenWhoRust/TomorrowNightTheme#25]
Could you please update?

**Comment by yangchoo** [comment]
fyi @izzetince I've built this locally and it seems to work for me.
[Tomorrow Night Theme-0.0.16.zip](https://github.com/MenWhoRust/TomorrowNightTheme/files/8488290/Tomorrow.Night.Theme-0.0.16.zip)
 
 Otherwise, you should be good once https://github.com/MenWhoRust/TomorrowNightTheme/pull/26 is merged and published.

**Comment by izzetince** [comment]
> fyi @izzetince I've built this locally and it seems to work for me when installing from disk. [Tomorrow Night Theme-0.0.16.zip](https://github.com/MenWhoRust/TomorrowNightTheme/files/8488290/Tomorrow.Night.Theme-0.0.16.zip)
> 
> Otherwise, you should be good once #26 is merged and published.

Thanks a lot. I'll try.
